
#ifndef _MAUDDEF_H_
#define _MAUDDEF_H_



typedef unsigned long				MAUDIO_AUDIOID;
typedef unsigned long				MAUDIO_POSITION;
typedef unsigned long				MAUDIO_INTERVAL;
typedef unsigned long				MAUDIO_LEVEL;
typedef unsigned long				MAUDIO_VORLEVEL;
typedef unsigned long				MAUDIO_VOLUME;
typedef unsigned long				MAUDIO_TIMEOUT;
typedef MAUDIO_POSITION	MAUDIO_LENGTH;

const MAUDIO_AUDIOID c_idInvalidAudio = 0;

const MAUDIO_VORLEVEL c_minVORLevel = 0;
const MAUDIO_VORLEVEL c_maxVORLevel = 100;

const MAUDIO_VOLUME c_minVolume = 0;
const MAUDIO_VOLUME c_maxVolume = 100;

const MAUDIO_POSITION c_posEOF = MAUDIO_POSITION(-1);
const MAUDIO_POSITION c_posBOF = MAUDIO_POSITION(-2);
const MAUDIO_POSITION c_posCurrent = MAUDIO_POSITION(-3);


enum MAUDIO_STATUS
{
	AUDIOSTATUS_STOP,
	AUDIOSTATUS_RUNNING,
	AUDIOSTATUS_PAUSE,
	AUDIOSTATUS_VOR
};


enum MAUDIO_INPUTTYPE
{
	AUDIOINPUT_NONE,
	AUDIOINPUT_FILE,
	AUDIOINPUT_RECEIVER,
	AUDIOINPUT_DRIVER
};


enum MAUDIO_OUTPUTTYPE
{
	AUDIOOUTPUT_NONE,
	AUDIOOUTPUT_FILE,
	AUDIOOUTPUT_SENDER,
	AUDIOOUTPUT_DRIVER
};


enum MAUDIO_SEEKORIGIN
{
	MAUDIO_SEEKBOF,
	MAUDIO_SEEKCURRENT,
	MAUDIO_SEEKEOF
};


enum MAUDIO_DATAFORMAT
{
	AUDIOFORMAT_UNKNOWN,
	AUDIOFORMAT_CELP,
	AUDIOFORMAT_LPCBB,
	AUDIOFORMAT_PCM_16M16,
	AUDIOFORMAT_PCM_16S16,
	AUDIOFORMAT_PCM_1M08,
	AUDIOFORMAT_PCM_1S08,
	AUDIOFORMAT_PCM_1M16,
	AUDIOFORMAT_PCM_1S16,
	AUDIOFORMAT_PCM_2M08,
	AUDIOFORMAT_PCM_2S08,
	AUDIOFORMAT_PCM_2M16,
	AUDIOFORMAT_PCM_2S16,
	AUDIOFORMAT_PCM_4M08,
	AUDIOFORMAT_PCM_4S08,
	AUDIOFORMAT_PCM_4M16,
	AUDIOFORMAT_PCM_4S16,
	AUDIOFORMAT_PCM_08M08,
	AUDIOFORMAT_PCM_08M16,
	AUDIOFORMAT_PCM_08S08,
	AUDIOFORMAT_PCM_08S16
};


#define SM_AUDIOFORMAT	MAUDIO_DATAFORMAT


enum MAUDIO_FILEFORMAT
{
	SMFILEFORMAT_UNKNOWN,
	SMFILEFORMAT_RIFF,
	SMFILEFORMAT_SMF
};


enum MAUDIO_OPENFLAG
{
	SMOPENFLAG_READ = 0,
	SMOPENFLAG_WRITE = 1,
	SMOPENFLAG_TRUNCATE = 2,
	SMOPENFLAG_WRITETRUNCATE = 3,
	SMOPENFLAG_NOCREATE = 4,
	SMOPENFLAG_WRITENOCREATE = 5,
	SMOPENFLAG_WRITETRUNCATENOCREATE = 7,
	SMOPENFLAG_DELETE = 8,
	SMOPENFLAG_WRITEDELETE = 9
};


const MAUDIO_DATAFORMAT c_defaultDataFormat = AUDIOFORMAT_PCM_16M16; 
const MAUDIO_FILEFORMAT c_defaultFileFormat = SMFILEFORMAT_RIFF;





#endif	// _MAUDDEF_H_
